// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.27.3
// source: camera-service.proto

package genproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetCameraStatusRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DeviceId string `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
}

func (x *GetCameraStatusRequest) Reset() {
	*x = GetCameraStatusRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_camera_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetCameraStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCameraStatusRequest) ProtoMessage() {}

func (x *GetCameraStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_camera_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCameraStatusRequest.ProtoReflect.Descriptor instead.
func (*GetCameraStatusRequest) Descriptor() ([]byte, []int) {
	return file_camera_service_proto_rawDescGZIP(), []int{0}
}

func (x *GetCameraStatusRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

type GetCameraStatusResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DeviceId string `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	IsOnline bool   `protobuf:"varint,2,opt,name=is_online,json=isOnline,proto3" json:"is_online,omitempty"`
}

func (x *GetCameraStatusResponse) Reset() {
	*x = GetCameraStatusResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_camera_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetCameraStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCameraStatusResponse) ProtoMessage() {}

func (x *GetCameraStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_camera_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCameraStatusResponse.ProtoReflect.Descriptor instead.
func (*GetCameraStatusResponse) Descriptor() ([]byte, []int) {
	return file_camera_service_proto_rawDescGZIP(), []int{1}
}

func (x *GetCameraStatusResponse) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *GetCameraStatusResponse) GetIsOnline() bool {
	if x != nil {
		return x.IsOnline
	}
	return false
}

var File_camera_service_proto protoreflect.FileDescriptor

var file_camera_service_proto_rawDesc = []byte{
	0x0a, 0x14, 0x63, 0x61, 0x6d, 0x65, 0x72, 0x61, 0x2d, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x73, 0x61, 0x6c, 0x61, 0x64, 0x69, 0x6e, 0x65,
	0x79, 0x65, 0x22, 0x35, 0x0a, 0x16, 0x47, 0x65, 0x74, 0x43, 0x61, 0x6d, 0x65, 0x72, 0x61, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09,
	0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x49, 0x64, 0x22, 0x53, 0x0a, 0x17, 0x47, 0x65, 0x74,
	0x43, 0x61, 0x6d, 0x65, 0x72, 0x61, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x49,
	0x64, 0x12, 0x1b, 0x0a, 0x09, 0x69, 0x73, 0x5f, 0x6f, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x69, 0x73, 0x4f, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x32, 0x6d,
	0x0a, 0x0d, 0x43, 0x61, 0x6d, 0x65, 0x72, 0x61, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12,
	0x5c, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x43, 0x61, 0x6d, 0x65, 0x72, 0x61, 0x53, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x12, 0x22, 0x2e, 0x73, 0x61, 0x6c, 0x61, 0x64, 0x69, 0x6e, 0x65, 0x79, 0x65, 0x2e,
	0x47, 0x65, 0x74, 0x43, 0x61, 0x6d, 0x65, 0x72, 0x61, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x23, 0x2e, 0x73, 0x61, 0x6c, 0x61, 0x64, 0x69, 0x6e,
	0x65, 0x79, 0x65, 0x2e, 0x47, 0x65, 0x74, 0x43, 0x61, 0x6d, 0x65, 0x72, 0x61, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x13, 0x5a,
	0x11, 0x2e, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x67, 0x65, 0x6e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_camera_service_proto_rawDescOnce sync.Once
	file_camera_service_proto_rawDescData = file_camera_service_proto_rawDesc
)

func file_camera_service_proto_rawDescGZIP() []byte {
	file_camera_service_proto_rawDescOnce.Do(func() {
		file_camera_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_camera_service_proto_rawDescData)
	})
	return file_camera_service_proto_rawDescData
}

var file_camera_service_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_camera_service_proto_goTypes = []any{
	(*GetCameraStatusRequest)(nil),  // 0: saladineye.GetCameraStatusRequest
	(*GetCameraStatusResponse)(nil), // 1: saladineye.GetCameraStatusResponse
}
var file_camera_service_proto_depIdxs = []int32{
	0, // 0: saladineye.CameraService.GetCameraStatus:input_type -> saladineye.GetCameraStatusRequest
	1, // 1: saladineye.CameraService.GetCameraStatus:output_type -> saladineye.GetCameraStatusResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_camera_service_proto_init() }
func file_camera_service_proto_init() {
	if File_camera_service_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_camera_service_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*GetCameraStatusRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_camera_service_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*GetCameraStatusResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_camera_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_camera_service_proto_goTypes,
		DependencyIndexes: file_camera_service_proto_depIdxs,
		MessageInfos:      file_camera_service_proto_msgTypes,
	}.Build()
	File_camera_service_proto = out.File
	file_camera_service_proto_rawDesc = nil
	file_camera_service_proto_goTypes = nil
	file_camera_service_proto_depIdxs = nil
}
