/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.8 */

#ifndef PB_SALADINEYE_MEDIA_SERVICE__GET_PHOTO_UPLOAD_URL_RESPONSE_PB_H_INCLUDED
#define PB_SALADINEYE_MEDIA_SERVICE__GET_PHOTO_UPLOAD_URL_RESPONSE_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _saladineye_GetPhotoUploadUrlResponse {
    char device_id[20];
    char upload_url[1000];
    char original_photo_path[200];
} saladineye_GetPhotoUploadUrlResponse;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define saladineye_GetPhotoUploadUrlResponse_init_default {"", "", ""}
#define saladineye_GetPhotoUploadUrlResponse_init_zero {"", "", ""}

/* Field tags (for use in manual encoding/decoding) */
#define saladineye_GetPhotoUploadUrlResponse_device_id_tag 1
#define saladineye_GetPhotoUploadUrlResponse_upload_url_tag 2
#define saladineye_GetPhotoUploadUrlResponse_original_photo_path_tag 3

/* Struct field encoding specification for nanopb */
#define saladineye_GetPhotoUploadUrlResponse_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   device_id,         1) \
X(a, STATIC,   SINGULAR, STRING,   upload_url,        2) \
X(a, STATIC,   SINGULAR, STRING,   original_photo_path,   3)
#define saladineye_GetPhotoUploadUrlResponse_CALLBACK NULL
#define saladineye_GetPhotoUploadUrlResponse_DEFAULT NULL

extern const pb_msgdesc_t saladineye_GetPhotoUploadUrlResponse_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define saladineye_GetPhotoUploadUrlResponse_fields &saladineye_GetPhotoUploadUrlResponse_msg

/* Maximum encoded size of messages (where known) */
#define SALADINEYE_MEDIA_SERVICE__GET_PHOTO_UPLOAD_URL_RESPONSE_PB_H_MAX_SIZE saladineye_GetPhotoUploadUrlResponse_size
#define saladineye_GetPhotoUploadUrlResponse_size 1225

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
