/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.8 */

#ifndef PB_SALADINEYE_MEDIA_SERVICE__GET_PHOTO_UPLOAD_URL_REQUEST_PB_H_INCLUDED
#define PB_SALADINEYE_MEDIA_SERVICE__GET_PHOTO_UPLOAD_URL_REQUEST_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _saladineye_GetPhotoUploadUrlRequest {
    pb_callback_t device_id;
    pb_callback_t original_photo_path;
} saladineye_GetPhotoUploadUrlRequest;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define saladineye_GetPhotoUploadUrlRequest_init_default {{{NULL}, NULL}, {{NULL}, NULL}}
#define saladineye_GetPhotoUploadUrlRequest_init_zero {{{NULL}, NULL}, {{NULL}, NULL}}

/* Field tags (for use in manual encoding/decoding) */
#define saladineye_GetPhotoUploadUrlRequest_device_id_tag 1
#define saladineye_GetPhotoUploadUrlRequest_original_photo_path_tag 2

/* Struct field encoding specification for nanopb */
#define saladineye_GetPhotoUploadUrlRequest_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   device_id,         1) \
X(a, CALLBACK, SINGULAR, STRING,   original_photo_path,   2)
#define saladineye_GetPhotoUploadUrlRequest_CALLBACK pb_default_field_callback
#define saladineye_GetPhotoUploadUrlRequest_DEFAULT NULL

extern const pb_msgdesc_t saladineye_GetPhotoUploadUrlRequest_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define saladineye_GetPhotoUploadUrlRequest_fields &saladineye_GetPhotoUploadUrlRequest_msg

/* Maximum encoded size of messages (where known) */
/* saladineye_GetPhotoUploadUrlRequest_size depends on runtime parameters */

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
